version: "3.8"

services:

  #DATABASE
  database:
    container_name: database_lab02
    image: postgres:14.1
    networks:
      - lab02_net
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database_lab02:/var/lib/postgresql
      - database_lab02_data:/var/lib/postgresql/data


networks:
  lab02_net:

volumes:
  database_lab02:
  database_lab02_data:
  rabbitmq_lab02_vol:

